import { ImageResponse } from "next/og"

// Generated by `bin/qie media og-default`. Override by dropping
// `app/opengraph-image.png` (or .jpg/.jpeg) into this directory; Next.js
// prefers static assets when present.

export const runtime = "edge"
export const alt = "Busybees"
export const size = { width: 1200, height: 630 }
export const contentType = "image/png"

export default async function OpengraphImage() {
  return new ImageResponse(
    (
      <div
        style={{
          width: "100%",
          height: "100%",
          display: "flex",
          flexDirection: "column",
          justifyContent: "center",
          padding: "80px",
          background:
            "linear-gradient(135deg, #0a0f0d 0%, #0f1a16 50%, #0a0f0d 100%)",
          color: "#f0f2f0",
          fontFamily: "sans-serif",
        }}
      >
        <div
          style={{
            fontSize: 112,
            fontWeight: 700,
            letterSpacing: "-0.03em",
            color: "#65BF95",
            lineHeight: 1.05,
          }}
        >
          Busybees
        </div>
        <div
          style={{
            marginTop: 28,
            fontSize: 36,
            color: "rgba(240, 242, 240, 0.72)",
            lineHeight: 1.25,
            maxWidth: 980,
          }}
        >
          Modern, safe and engaging indoor play space for children ages 0-6 in Lunenburg, Massachusetts. Day passes, birthday parties, monthly memberships, and special events for toddlers...
        </div>
      </div>
    ),
    { ...size },
  )
}
